### ISSUE TITLE
Review Mac OpenSSL instructions

### ISSUE THREAD

**Issue by ironfroggy** [caktus/developer-documentation#25]
```
brew install openssl
brew link openssl --force
```

**Comment by dchukhin** [comment]
Doing this worked for me, though it led to surprises later with [installing cryptography] (https://github.com/pyca/cryptography/issues/2138)

**Comment by ironfroggy** [comment]
@dchukhin can you explain how this was related?

**Comment by copelco** [comment]
On a side note, this is related to #12

**Comment by dchukhin** [comment]
Beginning with OS X 10.11 (El Capitan) Apple stopped including header files for OpenSSL.
When we install OpenSSL with Homebrew and link to it we are able to install and use virtualenvwrapper as noted in #12.

However, this apparently is a problem when installing cryptography because the OS X C preprocessor and linker use a different search order for OpenSSL.

This is explained in [this comment] (https://github.com/pyca/cryptography/issues/2138#issuecomment-121070718) and also [this issue] (https://github.com/Homebrew/homebrew/issues/41613)

It seems that setting the following variables is required in such situations, according to [cryptography docs] (https://cryptography.io/en/latest/installation/#building-cryptography-on-os-x):

`LDFLAGS="-L$(brew --prefix openssl)/lib"`
`CFLAGS="-I$(brew --prefix openssl)/include"`


Specifically, for the project I was working on I ended up installing cryptography with:
`env LDFLAGS="-L/opt/local/lib" CFLAGS="-I/opt/local/include" pip install cryptography`

**Comment by dchukhin** [comment]
Note: since [this] (https://github.com/Homebrew/brew/pull/597) we can no longer `brew link openssl --force`
